/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   op_codes.c                                         :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: vvaucoul <vvaucoul@student.42.fr>          +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2023/12/07 20:36:20 by vvaucoul          #+#    #+#             */
/*   Updated: 2024/01/23 15:23:15 by vvaucoul         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include <woody.h>

/**
 * @brief Get the op code value
 *
 * This file provide functions to get the op code value
 * OpCode value is automatically generated by the 'woody_opcodes' (woody_opcodes.c)
 */

// ! ||--------------------------------------------------------------------------------||
// ! ||                               INTERFACE FUNCTIONS                              ||
// ! ||--------------------------------------------------------------------------------||

unsigned char *get_op_code() {
    return (woody);
}

uint32_t get_op_code_size() {
    return (woody_len);
}